#!/usr/bin/env python3
"""Build the embedded Polaris field catalog from CDS VizieR Hipparcos data."""

from __future__ import annotations

import csv
import datetime as dt
import pathlib
import urllib.parse
import urllib.request


ROOT = pathlib.Path(__file__).resolve().parents[1]
CSV_PATH = ROOT / "resources" / "catalog" / "polaris_field.csv"
README_PATH = ROOT / "resources" / "catalog" / "README.md"
DATA_HEADER_PATH = ROOT / "src" / "PolarisCatalogData.h"
POLARIS_HIP = 11767
HIPPARCOS_EPOCH_YEAR = "1991.25"


def vizier_url() -> str:
    query = {
        "-source": "I/239/hip_main",
        "-out": "HIP,RAICRS,DEICRS,pmRA,pmDE,Hpmag",
        "DEICRS": ">86",
        "Hpmag": "<9.5",
        "-out.max": "2000",
    }
    return "https://vizier.cds.unistra.fr/viz-bin/asu-tsv?" + urllib.parse.urlencode(query)


def fetch_rows() -> list[dict[str, str]]:
    with urllib.request.urlopen(vizier_url(), timeout=60) as response:
        text = response.read().decode("utf-8")

    lines = [line for line in text.splitlines() if line and not line.startswith("#")]
    header_index = next(i for i, line in enumerate(lines) if line.startswith("HIP\t"))
    data_lines = [
        line
        for line in lines[header_index + 3 :]
        if line.strip() and not line.startswith("-")
    ]
    reader = csv.DictReader([lines[header_index], *data_lines], delimiter="\t")
    rows = []
    for row in reader:
        if not row.get("HIP", "").strip():
            continue
        hip = int(row["HIP"])
        rows.append(
            {
                "source_id": str(hip),
                "name": "Polaris" if hip == POLARIS_HIP else f"HIP {hip}",
                "ra_deg_j1991_25": f'{float(row["RAICRS"]):.8f}',
                "dec_deg_j1991_25": f'{float(row["DEICRS"]):.8f}',
                "pmra_mas_yr": f'{float(row["pmRA"]):.2f}',
                "pmdec_mas_yr": f'{float(row["pmDE"]):.2f}',
                "mag": f'{float(row["Hpmag"]):.4f}',
                "is_polaris": "true" if hip == POLARIS_HIP else "false",
            }
        )
    rows.sort(key=lambda item: int(item["source_id"]))
    return rows


def write_csv(rows: list[dict[str, str]]) -> None:
    CSV_PATH.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "source_id",
        "name",
        "ra_deg_j1991_25",
        "dec_deg_j1991_25",
        "pmra_mas_yr",
        "pmdec_mas_yr",
        "mag",
        "is_polaris",
    ]
    with CSV_PATH.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def cpp_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_data_header(rows: list[dict[str, str]]) -> None:
    lines = [
        "#pragma once",
        "",
        "// Generated by tools/build_polaris_catalog.py.",
        "// Source: CDS VizieR I/239/hip_main, Hipparcos Main Catalogue.",
        "",
        "inline const CatalogStar kPolarisCatalogStars[] = {",
    ]
    for row in rows:
        lines.append(
            "    {"
            f'{row["source_id"]}ULL, '
            f'{cpp_string(row["name"])}, '
            f'{row["ra_deg_j1991_25"]}, '
            f'{row["dec_deg_j1991_25"]}, '
            f"{HIPPARCOS_EPOCH_YEAR}, "
            f'{row["pmra_mas_yr"]}, '
            f'{row["pmdec_mas_yr"]}, '
            f'{row["mag"]}, '
            f'{row["is_polaris"]}'
            "},"
        )
    lines.extend(["};", ""])
    DATA_HEADER_PATH.write_text("\n".join(lines), encoding="utf-8")


def write_readme(row_count: int) -> None:
    generated_date = dt.date.today().isoformat()
    README_PATH.write_text(
        "\n".join(
            [
                "# Polaris Field Catalog",
                "",
                "This directory contains the generated development artifact used to build",
                "the embedded Polaris alignment catalog.",
                "",
                "- Data source: Hipparcos Main Catalogue, ESA 1997.",
                "- Access service: CDS VizieR.",
                "- VizieR table: I/239/hip_main.",
                "- Coordinate system: ICRS, epoch J1991.25 as published by Hipparcos.",
                "- Embedded epoch field: catalogEpochYear = 1991.25 for every row.",
                "- Query region: dec > 86 degrees.",
                "- Magnitude limit: Hpmag <= 9.5.",
                f"- Generated date: {generated_date}.",
                f"- Generated row count: {row_count}.",
                f"- Generation command: python tools/build_polaris_catalog.py",
                "",
                "The production application does not query VizieR at runtime. The C++",
                "runtime uses src/PolarisCatalogData.h, generated from the CSV in this",
                "directory.",
                "",
                "Source landing page: https://cdsarc.cds.unistra.fr/viz-bin/cat/I/239",
                "VizieR query endpoint: https://vizier.cds.unistra.fr/viz-bin/asu-tsv",
                "",
            ]
        ),
        encoding="utf-8",
    )


def main() -> None:
    rows = fetch_rows()
    if len(rows) < 80:
        raise RuntimeError(f"Expected at least 80 catalog rows, got {len(rows)}")
    if sum(row["is_polaris"] == "true" for row in rows) != 1:
        raise RuntimeError("Expected exactly one Polaris row")
    write_csv(rows)
    write_data_header(rows)
    write_readme(len(rows))


if __name__ == "__main__":
    main()
